### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by kumavis** [luniehq/cosmos-keys#18]
in node
```
ReferenceError: window is not defined
    at Object.<anonymous> (/home/xyz/Development/cosmos-key/node_modules/@lunie/cosmos-keys/lib/cosmos-keys.js:1:224)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/xyz/Development/cosmos-key/index.js:3:34)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```

work around:
```js
global.window = global
require(...)
```

**Comment by webmaster128** [comment]
Before being shipped to npm, cosmos-keys is built for the Webpack target `web` (the default). Since there is no separate WebPack build for node, I would not expect the package to reliably run in Node.js at all. See https://webpack.js.org/concepts/targets/ and https://webpack.js.org/configuration/target/.
